import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import StyledComponentsRegistry from "@/lib/antd.registry";
import Head from "next/head";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Provider from "@/core/Provider";
import TicketContextProvider from "@/store/UseContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Head>
        <>
          <>
            <link
              rel='stylesheet'
              type='text/css'
              charSet='UTF-8'
              href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css'
            />
            <link
              rel='stylesheet'
              type='text/css'
              href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css'
            />
          </>
        </>
        <>
          <link
            rel='stylesheet'
            href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css'
            integrity='sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ=='
            crossOrigin='anonymous'
            referrerPolicy='no-referrer'
          />
       
        </>
      </Head>

      <body className={inter.className}>
        <Provider>
          <TicketContextProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </TicketContextProvider>
        </Provider>
       
      </body>
    </html>
  );
}
